version: '3'

vars:
  STATE_FILE: /var/lib/vps-setup-state

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  status:
    desc: Show setup progress
    cmds:
      - |
        echo ""
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo "  VPS Setup Status"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""
        for i in 1 2 3 4; do
          if grep -q "^TASK_${i}_COMPLETE=1$" {{.STATE_FILE}} 2>/dev/null; then
            case $i in
              1) echo "  ✓ Task 1: Secure Server" ;;
              2) echo "  ✓ Task 2: Install Docker" ;;
              3) echo "  ✓ Task 3: Install Coolify" ;;
              4) echo "  ✓ Task 4: Cloudflare Tunnel" ;;
            esac
          else
            case $i in
              1) echo "  ○ Task 1: Secure Server" ;;
              2) echo "  ○ Task 2: Install Docker" ;;
              3) echo "  ○ Task 3: Install Coolify" ;;
              4) echo "  ○ Task 4: Cloudflare Tunnel" ;;
            esac
          fi
        done
        echo ""

  reset:
    desc: Reset progress and start over
    cmds:
      - rm -f {{.STATE_FILE}}
      - echo "✓ Progress reset"

  all:
    desc: Run all remaining tasks
    cmds:
      - task: 1-secure
      - task: 2-docker
      - task: 3-coolify
      - task: 4-tunnel
      - task: status

  # ==========================================================================
  # Task 1: Secure Server
  # ==========================================================================
  1-secure:
    desc: "Task 1: Secure server (SSH, firewall, fail2ban)"
    status:
      - grep -q "^TASK_1_COMPLETE=1$" {{.STATE_FILE}} 2>/dev/null
    cmds:
      - echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
      - echo "  Task 1/4: Secure Server"
      - echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
      - bash scripts/01-secure-server.sh
      - echo "TASK_1_COMPLETE=1" >> {{.STATE_FILE}}
      - echo ""
      - echo "✓ Task 1 complete!"
      - echo ""
      - echo "⚠ CHECKPOINT: Verify you can still SSH in from another terminal!"

  # ==========================================================================
  # Task 2: Install Docker
  # ==========================================================================
  2-docker:
    desc: "Task 2: Install Docker"
    status:
      - grep -q "^TASK_2_COMPLETE=1$" {{.STATE_FILE}} 2>/dev/null
    cmds:
      - echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
      - echo "  Task 2/4: Install Docker"
      - echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
      - bash scripts/02-install-docker.sh
      - echo "TASK_2_COMPLETE=1" >> {{.STATE_FILE}}
      - echo ""
      - echo "✓ Task 2 complete!"

  # ==========================================================================
  # Task 3: Install Coolify
  # ==========================================================================
  3-coolify:
    desc: "Task 3: Install Coolify"
    status:
      - grep -q "^TASK_3_COMPLETE=1$" {{.STATE_FILE}} 2>/dev/null
    cmds:
      - echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
      - echo "  Task 3/4: Install Coolify"
      - echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
      - bash scripts/03-install-coolify.sh
      - echo "TASK_3_COMPLETE=1" >> {{.STATE_FILE}}
      - echo ""
      - echo "✓ Task 3 complete!"
      - echo ""
      - echo "⚠ CHECKPOINT: Open http://$(curl -s ifconfig.me):8000 and create your admin account"

  # ==========================================================================
  # Task 4: Cloudflare Tunnel
  # ==========================================================================
  4-tunnel:
    desc: "Task 4: Setup Cloudflare Tunnel"
    status:
      - grep -q "^TASK_4_COMPLETE=1$" {{.STATE_FILE}} 2>/dev/null
    cmds:
      - echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
      - echo "  Task 4/4: Cloudflare Tunnel"
      - echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
      - bash scripts/04-setup-cloudflare-tunnel.sh
      - echo "TASK_4_COMPLETE=1" >> {{.STATE_FILE}}
      - echo ""
      - echo "✓ Task 4 complete!"

  # ==========================================================================
  # Post-setup tasks
  # ==========================================================================
  lockdown:
    desc: "Remove temporary port 8000 access (run after tunnel works)"
    cmds:
      - ufw delete allow 8000
      - echo "✓ Port 8000 closed. Access Coolify via Cloudflare Tunnel only."

  # ==========================================================================
  # Utility tasks
  # ==========================================================================
  install-task:
    desc: Install Task (taskfile.dev) on this system
    cmds:
      - sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
      - echo "✓ Task installed"

